import win32con

KEY_MAP = {
    'ENTER': win32con.VK_RETURN,
    'ESC': win32con.VK_ESCAPE,
    'F1': win32con.VK_F1,
    'F2': win32con.VK_F2,
    'F3': win32con.VK_F3,
    'F4': win32con.VK_F4,
    'F5': win32con.VK_F5,
    'F6': win32con.VK_F6,
    'F7': win32con.VK_F7,
    'F8': win32con.VK_F8,
    'F9': win32con.VK_F9,
    'F10': win32con.VK_F10,
    'F11': win32con.VK_F11,
    'F12': win32con.VK_F12,
    'CTRL': win32con.VK_CONTROL,
    'ALT': win32con.VK_MENU,
    'SHIFT': win32con.VK_SHIFT,
    'TAB': win32con.VK_TAB,
    'CAPSLOCK': win32con.VK_CAPITAL,
    'DEL': win32con.VK_DELETE,
    'INSERT': win32con.VK_INSERT,
    'HOME': win32con.VK_HOME,
    'END': win32con.VK_END,
    'PAGEUP': win32con.VK_PRIOR,
    'PAGEDOWN': win32con.VK_NEXT,
    'WIN': win32con.VK_LWIN,
    'UP': win32con.VK_UP,
    'DOWN': win32con.VK_DOWN,
    'LEFT': win32con.VK_LEFT,
    'RIGHT': win32con.VK_RIGHT,
    '+': win32con.VK_ADD,
    '-': win32con.VK_SUBTRACT,
    '*': win32con.VK_MULTIPLY,
    '/': win32con.VK_DIVIDE
} 